from .availability import availability_system_prompt
from .macrocycles import macrocycle_system_prompt
from .mesocycles import mesocycle_system_prompt
from .microcycles import microcycle_system_prompt
from .phase_components import phase_component_system_prompt
from .workout_schedule import workout_schedule_system_prompt
from .workout_completion import workout_complete_system_prompt
from .main_agent import goal_extraction_system_prompt