from app.models import Phase_Component_Bodyparts
#([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)
#    Phase_Component_Bodyparts(id=1, bodypart_id=$1, component_id=$2, phase_id=$3, required_within_microcycle="$4"),
component_bodyparts = [
    Phase_Component_Bodyparts(id=1, bodypart_id=1, component_id=6, phase_id=1, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=2, bodypart_id=2, component_id=6, phase_id=1, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=3, bodypart_id=3, component_id=6, phase_id=1, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=4, bodypart_id=4, component_id=6, phase_id=1, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=5, bodypart_id=5, component_id=6, phase_id=1, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=6, bodypart_id=6, component_id=6, phase_id=1, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=7, bodypart_id=7, component_id=6, phase_id=1, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=8, bodypart_id=1, component_id=6, phase_id=2, required_within_microcycle="optional"),
    Phase_Component_Bodyparts(id=9, bodypart_id=2, component_id=6, phase_id=2, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=10, bodypart_id=3, component_id=6, phase_id=2, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=11, bodypart_id=4, component_id=6, phase_id=2, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=12, bodypart_id=5, component_id=6, phase_id=2, required_within_microcycle="optional"),
    Phase_Component_Bodyparts(id=13, bodypart_id=6, component_id=6, phase_id=2, required_within_microcycle="optional"),
    Phase_Component_Bodyparts(id=14, bodypart_id=7, component_id=6, phase_id=2, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=15, bodypart_id=1, component_id=6, phase_id=3, required_within_microcycle="optional"),
    Phase_Component_Bodyparts(id=16, bodypart_id=2, component_id=6, phase_id=3, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=17, bodypart_id=3, component_id=6, phase_id=3, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=18, bodypart_id=4, component_id=6, phase_id=3, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=19, bodypart_id=5, component_id=6, phase_id=3, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=20, bodypart_id=6, component_id=6, phase_id=3, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=21, bodypart_id=7, component_id=6, phase_id=3, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=22, bodypart_id=1, component_id=6, phase_id=4, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=23, bodypart_id=2, component_id=6, phase_id=4, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=24, bodypart_id=3, component_id=6, phase_id=4, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=25, bodypart_id=4, component_id=6, phase_id=4, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=26, bodypart_id=5, component_id=6, phase_id=4, required_within_microcycle="optional"),
    Phase_Component_Bodyparts(id=27, bodypart_id=6, component_id=6, phase_id=4, required_within_microcycle="optional"),
    Phase_Component_Bodyparts(id=28, bodypart_id=7, component_id=6, phase_id=4, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=29, bodypart_id=1, component_id=6, phase_id=5, required_within_microcycle="optional"),
    Phase_Component_Bodyparts(id=30, bodypart_id=2, component_id=6, phase_id=5, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=31, bodypart_id=3, component_id=6, phase_id=5, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=32, bodypart_id=4, component_id=6, phase_id=5, required_within_microcycle="always"),
    Phase_Component_Bodyparts(id=33, bodypart_id=5, component_id=6, phase_id=5, required_within_microcycle="optional"),
    Phase_Component_Bodyparts(id=34, bodypart_id=6, component_id=6, phase_id=5, required_within_microcycle="optional"),
    Phase_Component_Bodyparts(id=35, bodypart_id=7, component_id=6, phase_id=5, required_within_microcycle="always"),
]