
#([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)
#    Phase_Breakdown(phase_no=$1,\n        phase="$2",\n        component="$3",\n        subcomponent="$4",\n        sub_component="$5",\n        reps_min=$6,\n        reps_max=$7,\n        sets_min=$8,\n        sets_max=$9,\n        tempo="$10",\n        Seconds_Per_Exercise=$11,\n        intensity_min=$12,\n        intensity_max=$13,\n        rest_min=$14,\n        rest_max=$15,\n        Required_every_workout=$16,\n        Required_within_microcycle=$17,\n        frequency_per_microcycle_min=$18,\n        frequency_per_microcycle_max=$19,\n        exercises_per_bodypart_workout_min=$20,\n        exercises_per_bodypart_workout_max=$21,\n        exercise_selection_note="$22"),\n

#([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)
#    Phase_Breakdown(phase_no=$1,\n        phase="$2",\n        component="$3",\n        subcomponent="$4",\n        sub_component="$5",\n        reps_min=$6,\n        reps_max=$7,\n        sets_min=$8,\n        sets_max=$9,\n        tempo="$10",\n        Seconds_Per_Exercise=$11,\n        intensity_min=$12,\n        intensity_max=$13,\n        rest_min=$14,\n        rest_max=$15,\n        Required_every_workout=$16,\n        Required_within_microcycle=$17,\n        frequency_per_microcycle_min=$18,\n        frequency_per_microcycle_max=$19,\n        exercises_per_bodypart_workout_min=$20,\n        exercises_per_bodypart_workout_max=$21,\n        exercise_selection_note=None),\n



#([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)
#    Phase_Breakdown(\n        phase_no=$1,\n        phase="$2",\n        component="$3",\n        subcomponent="$4",\n        sub_component="$5",\n        reps_min=$6, reps_max=$7,\n        sets_min=$8, sets_max=$9,\n        tempo="$10",\n        Seconds_Per_Exercise=$11,\n        intensity_min=$12, intensity_max=$13,\n        rest_min=$14, rest_max=$15,\n        Required_every_workout="$16", Required_within_microcycle="$17",\n        frequency_per_microcycle_min=$18, frequency_per_microcycle_max=$19,\n        exercises_per_bodypart_workout_min=$20, exercises_per_bodypart_workout_max=$21,\n        exercise_selection_note="$22"),\n

#([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)	([^	)]+)
#    Phase_Breakdown(\n        phase_no=$1,\n        phase="$2",\n        component="$3",\n        subcomponent="$4",\n        sub_component="$5",\n        reps_min=$6, reps_max=$7,\n        sets_min=$8, sets_max=$9,\n        tempo="$10",\n        Seconds_Per_Exercise=$11,\n        intensity_min=$12, intensity_max=$13,\n        rest_min=$14, rest_max=$15,\n        Required_every_workout="$16", Required_within_microcycle="$17",\n        frequency_per_microcycle_min=$18, frequency_per_microcycle_max=$19,\n        exercises_per_bodypart_workout_min=$20, exercises_per_bodypart_workout_max=$21,\n        exercise_selection_note=None),\n
from app.models import Phase_Breakdown



NA = None

phase_breakdown = [
    Phase_Breakdown(
        phase_no=1,
        phase="Stabilization_Endurance",
        component="Flexibility",
        subcomponent="stabilization",
        sub_component="flexibility-stabilization",
        reps_min=1, reps_max=1,
        sets_min=1, sets_max=3,
        tempo="30 s hold",
        Seconds_Per_Exercise=30,
        intensity_min=None, intensity_max=None,
        rest_min=0, rest_max=0,
        Required_every_workout=True, Required_within_microcycle="always",
        frequency_per_microcycle_min=NA, frequency_per_microcycle_max=NA,
        exercises_per_bodypart_workout_min=None, exercises_per_bodypart_workout_max=None,
        exercise_selection_note="SMR and static"),

    Phase_Breakdown(
        phase_no=1,
        phase="Stabilization_Endurance",
        component="Core",
        subcomponent="stabilization",
        sub_component="core-stabilization",
        reps_min=12, reps_max=20,
        sets_min=1, sets_max=4,
        tempo="Slow 4/2/1",
        Seconds_Per_Exercise=7,
        intensity_min=None, intensity_max=None,
        rest_min=30, rest_max=90,
        Required_every_workout=False, Required_within_microcycle="always",
        frequency_per_microcycle_min=2, frequency_per_microcycle_max=4,
        exercises_per_bodypart_workout_min=1, exercises_per_bodypart_workout_max=4,
        exercise_selection_note=None),
	
    Phase_Breakdown(
        phase_no=1,
        phase="Stabilization_Endurance",
        component="Balance",
        subcomponent="stabilization",
        sub_component="balance-stabilization",
        reps_min=12, reps_max=20,
        sets_min=1, sets_max=3,
        tempo="Slow 4/2/1",
        Seconds_Per_Exercise=7,
        intensity_min=None, intensity_max=None,
        rest_min=30, rest_max=90,
        Required_every_workout=False, Required_within_microcycle="always",
        frequency_per_microcycle_min=2, frequency_per_microcycle_max=4,
        exercises_per_bodypart_workout_min=1, exercises_per_bodypart_workout_max=4,
        exercise_selection_note="for SL exercises half the reps"),

    Phase_Breakdown(
        phase_no=1,
        phase="Stabilization_Endurance",
        component="Plyometric",
        subcomponent="stabilization",
        sub_component="plyometric-stabilization",
        reps_min=5, reps_max=8,
        sets_min=1, sets_max=3,
        tempo="3-5 s hold on landing",
        Seconds_Per_Exercise=5,
        intensity_min=None, intensity_max=None,
        rest_min=30, rest_max=90,
        Required_every_workout=False, Required_within_microcycle="after core and balance sufficient",
        frequency_per_microcycle_min=2, frequency_per_microcycle_max=4,
        exercises_per_bodypart_workout_min=0, exercises_per_bodypart_workout_max=2,
        exercise_selection_note=None),
	
    Phase_Breakdown(
        phase_no=1,
        phase="Stabilization_Endurance",
        component="SAQ",
        subcomponent="strength",
        sub_component="SAQ-strength",
        reps_min=2, reps_max=3,
        sets_min=1, sets_max=2,
        tempo="Moderate",
        Seconds_Per_Exercise=NA,
        intensity_min=None, intensity_max=None,
        rest_min=30, rest_max=90,
        Required_every_workout=False, Required_within_microcycle="after core and balance sufficient",
        frequency_per_microcycle_min=2, frequency_per_microcycle_max=4,
        exercises_per_bodypart_workout_min=4, exercises_per_bodypart_workout_max=6,
        exercise_selection_note="drills with limited horizontal inertia and unpredictability"),

    Phase_Breakdown(
        phase_no=1,
        phase="Stabilization_Endurance",
        component="Resistance",
        subcomponent="stabilization",
        sub_component="resistance-stabilization",
        reps_min=12, reps_max=20,
        sets_min=1, sets_max=3,
        tempo="Slow 4/2/1",
        Seconds_Per_Exercise=7,
        intensity_min=50, intensity_max=70,
        rest_min=30, rest_max=90,
        Required_every_workout=False, Required_within_microcycle="always",
        frequency_per_microcycle_min=2, frequency_per_microcycle_max=4,
        exercises_per_bodypart_workout_min=1, exercises_per_bodypart_workout_max=2,
        exercise_selection_note="stabilization progression"),

    Phase_Breakdown(
        phase_no=2,
        phase="Strength_Endurance",
        component="Flexibility",
        subcomponent="strength",
        sub_component="flexibility-strength",
        reps_min=5, reps_max=10,
        sets_min=1, sets_max=2,
        tempo="1-2 s hold",
        Seconds_Per_Exercise=2,
        intensity_min=None, intensity_max=None,
        rest_min=0, rest_max=0,
        Required_every_workout=True, Required_within_microcycle="always",
        frequency_per_microcycle_min=NA, frequency_per_microcycle_max=NA,
        exercises_per_bodypart_workout_min=None, exercises_per_bodypart_workout_max=None,
        exercise_selection_note="SMR and active; static optional"),

    Phase_Breakdown(
        phase_no=2,
        phase="Strength_Endurance",
        component="Core",
        subcomponent="strength",
        sub_component="core-strength",
        reps_min=8, reps_max=12,
        sets_min=2, sets_max=3,
        tempo="Medium",
        Seconds_Per_Exercise=None,
        intensity_min=None, intensity_max=None,
        rest_min=30, rest_max=60,
        Required_every_workout=False, Required_within_microcycle="always",
        frequency_per_microcycle_min=2, frequency_per_microcycle_max=4,
        exercises_per_bodypart_workout_min=1, exercises_per_bodypart_workout_max=3,
        exercise_selection_note=None),
	
    Phase_Breakdown(
        phase_no=2,
        phase="Strength_Endurance",
        component="Balance",
        subcomponent="strength",
        sub_component="balance-strength",
        reps_min=8, reps_max=12,
        sets_min=2, sets_max=3,
        tempo="Medium",
        Seconds_Per_Exercise=None,
        intensity_min=None, intensity_max=None,
        rest_min=30, rest_max=60,
        Required_every_workout=False, Required_within_microcycle="always",
        frequency_per_microcycle_min=2, frequency_per_microcycle_max=4,
        exercises_per_bodypart_workout_min=1, exercises_per_bodypart_workout_max=3,
        exercise_selection_note=None),
	
    Phase_Breakdown(
        phase_no=2,
        phase="Strength_Endurance",
        component="Plyometric",
        subcomponent="strength",
        sub_component="plyometric-strength",
        reps_min=8, reps_max=10,
        sets_min=2, sets_max=3,
        tempo="Repeating",
        Seconds_Per_Exercise=None,
        intensity_min=None, intensity_max=None,
        rest_min=30, rest_max=60,
        Required_every_workout=False, Required_within_microcycle="always",
        frequency_per_microcycle_min=2, frequency_per_microcycle_max=4,
        exercises_per_bodypart_workout_min=1, exercises_per_bodypart_workout_max=3,
        exercise_selection_note=None),
	
    Phase_Breakdown(
        phase_no=2,
        phase="Strength_Endurance",
        component="SAQ",
        subcomponent="strength",
        sub_component="SAQ-strength",
        reps_min=3, reps_max=5,
        sets_min=3, sets_max=4,
        tempo="Fast",
        Seconds_Per_Exercise=None,
        intensity_min=None, intensity_max=None,
        rest_min=30, rest_max=60,
        Required_every_workout=False, Required_within_microcycle="optional but recommended",
        frequency_per_microcycle_min=2, frequency_per_microcycle_max=4,
        exercises_per_bodypart_workout_min=6, exercises_per_bodypart_workout_max=8,
        exercise_selection_note="drills allowing greater horizontal inertia but limited unpredictability"),

    Phase_Breakdown(
        phase_no=2,
        phase="Strength_Endurance",
        component="Resistance",
        subcomponent="strength",
        sub_component="resistance-strength",
        reps_min=8, reps_max=12,
        sets_min=2, sets_max=4,
        tempo="2/0/2",
        Seconds_Per_Exercise=4,
        intensity_min=70, intensity_max=80,
        rest_min=30, rest_max=60,
        Required_every_workout=False, Required_within_microcycle="always",
        frequency_per_microcycle_min=2, frequency_per_microcycle_max=4,
        exercises_per_bodypart_workout_min=1, exercises_per_bodypart_workout_max=1,
        exercise_selection_note="first part of superset"),

    Phase_Breakdown(
        phase_no=2,
        phase="Strength_Endurance",
        component="Resistance",
        subcomponent="stabilization",
        sub_component="resistance-stabilization",
        reps_min=8, reps_max=12,
        sets_min=2, sets_max=4,
        tempo="4/2/1",
        Seconds_Per_Exercise=7,
        intensity_min=70, intensity_max=80,
        rest_min=30, rest_max=60,
        Required_every_workout=False, Required_within_microcycle="always",
        frequency_per_microcycle_min=2, frequency_per_microcycle_max=4,
        exercises_per_bodypart_workout_min=1, exercises_per_bodypart_workout_max=1,
        exercise_selection_note="second part of superset"),

    Phase_Breakdown(
        phase_no=3,
        phase="Hypertrophy",
        component="Flexibility",
        subcomponent="strength",
        sub_component="flexibility-strength",
        reps_min=5, reps_max=10,
        sets_min=1, sets_max=2,
        tempo="1-2 s hold",
        Seconds_Per_Exercise=2,
        intensity_min=None, intensity_max=None,
        rest_min=0, rest_max=0,
        Required_every_workout=True, Required_within_microcycle="always",
        frequency_per_microcycle_min=NA, frequency_per_microcycle_max=NA,
        exercises_per_bodypart_workout_min=None, exercises_per_bodypart_workout_max=None,
        exercise_selection_note="SMR and active; static optional"),

    Phase_Breakdown(
        phase_no=3,
        phase="Hypertrophy",
        component="Core",
        subcomponent="strength",
        sub_component="core-strength",
        reps_min=8, reps_max=12,
        sets_min=2, sets_max=3,
        tempo="Medium",
        Seconds_Per_Exercise=None,
        intensity_min=None, intensity_max=None,
        rest_min=30, rest_max=60,
        Required_every_workout=False, Required_within_microcycle="optional but recommended",
        frequency_per_microcycle_min=3, frequency_per_microcycle_max=6,
        exercises_per_bodypart_workout_min=0, exercises_per_bodypart_workout_max=4,
        exercise_selection_note=None),
	
    Phase_Breakdown(
        phase_no=3,
        phase="Hypertrophy",
        component="Balance",
        subcomponent="strength",
        sub_component="balance-strength",
        reps_min=8, reps_max=12,
        sets_min=2, sets_max=3,
        tempo="Medium",
        Seconds_Per_Exercise=None,
        intensity_min=None, intensity_max=None,
        rest_min=30, rest_max=60,
        Required_every_workout=False, Required_within_microcycle="optional but recommended",
        frequency_per_microcycle_min=3, frequency_per_microcycle_max=6,
        exercises_per_bodypart_workout_min=0, exercises_per_bodypart_workout_max=4,
        exercise_selection_note=None),
	
    Phase_Breakdown(
        phase_no=3,
        phase="Hypertrophy",
        component="Plyometric",
        subcomponent="strength",
        sub_component="plyometric-strength",
        reps_min=8, reps_max=10,
        sets_min=2, sets_max=3,
        tempo="Repeating",
        Seconds_Per_Exercise=None,
        intensity_min=None, intensity_max=None,
        rest_min=30, rest_max=60,
        Required_every_workout=False, Required_within_microcycle="optional but recommended",
        frequency_per_microcycle_min=3, frequency_per_microcycle_max=6,
        exercises_per_bodypart_workout_min=0, exercises_per_bodypart_workout_max=4,
        exercise_selection_note=None),
	
    Phase_Breakdown(
        phase_no=3,
        phase="Hypertrophy",
        component="SAQ",
        subcomponent="strength",
        sub_component="SAQ-strength",
        reps_min=3, reps_max=5,
        sets_min=3, sets_max=4,
        tempo="Fast",
        Seconds_Per_Exercise=None,
        intensity_min=None, intensity_max=None,
        rest_min=30, rest_max=60,
        Required_every_workout=False, Required_within_microcycle="optional but recommended",
        frequency_per_microcycle_min=2, frequency_per_microcycle_max=4,
        exercises_per_bodypart_workout_min=6, exercises_per_bodypart_workout_max=8,
        exercise_selection_note="drills allowing greater horizontal inertia but limited unpredictability"),

    Phase_Breakdown(
        phase_no=3,
        phase="Hypertrophy",
        component="Resistance",
        subcomponent="strength",
        sub_component="resistance-strength",
        reps_min=6, reps_max=12,
        sets_min=3, sets_max=5,
        tempo="2/0/2",
        Seconds_Per_Exercise=4,
        intensity_min=75, intensity_max=85,
        rest_min=30, rest_max=60,
        Required_every_workout=False, Required_within_microcycle="always",
        frequency_per_microcycle_min=3, frequency_per_microcycle_max=6,
        exercises_per_bodypart_workout_min=2, exercises_per_bodypart_workout_max=4,
        exercise_selection_note=None),
	
    Phase_Breakdown(
        phase_no=4,
        phase="Maximal_Strength",
        component="Flexibility",
        subcomponent="strength",
        sub_component="flexibility-strength",
        reps_min=5, reps_max=10,
        sets_min=1, sets_max=2,
        tempo="1-2 s hold",
        Seconds_Per_Exercise=2,
        intensity_min=None, intensity_max=None,
        rest_min=0, rest_max=0,
        Required_every_workout=True, Required_within_microcycle="always",
        frequency_per_microcycle_min=NA, frequency_per_microcycle_max=NA,
        exercises_per_bodypart_workout_min=None, exercises_per_bodypart_workout_max=None,
        exercise_selection_note="SMR and active; static optional"),

    Phase_Breakdown(
        phase_no=4,
        phase="Maximal_Strength",
        component="Core",
        subcomponent="strength",
        sub_component="core-strength",
        reps_min=8, reps_max=12,
        sets_min=2, sets_max=3,
        tempo="Medium 1/1/1",
        Seconds_Per_Exercise=3,
        intensity_min=None, intensity_max=None,
        rest_min=30, rest_max=60,
        Required_every_workout=False, Required_within_microcycle="optional but recommended",
        frequency_per_microcycle_min=2, frequency_per_microcycle_max=4,
        exercises_per_bodypart_workout_min=0, exercises_per_bodypart_workout_max=3,
        exercise_selection_note=None),
	
    Phase_Breakdown(
        phase_no=4,
        phase="Maximal_Strength",
        component="Balance",
        subcomponent="strength",
        sub_component="balance-strength",
        reps_min=8, reps_max=12,
        sets_min=2, sets_max=3,
        tempo="Medium 1/1/1",
        Seconds_Per_Exercise=3,
        intensity_min=None, intensity_max=None,
        rest_min=30, rest_max=60,
        Required_every_workout=False, Required_within_microcycle="optional but recommended",
        frequency_per_microcycle_min=2, frequency_per_microcycle_max=4,
        exercises_per_bodypart_workout_min=0, exercises_per_bodypart_workout_max=3,
        exercise_selection_note=None),
	
    Phase_Breakdown(
        phase_no=4,
        phase="Maximal_Strength",
        component="Plyometric",
        subcomponent="strength",
        sub_component="plyometric-strength",
        reps_min=8, reps_max=10,
        sets_min=2, sets_max=3,
        tempo="Repeating",
        Seconds_Per_Exercise=None,
        intensity_min=None, intensity_max=None,
        rest_min=30, rest_max=60,
        Required_every_workout=False, Required_within_microcycle="optional but recommended",
        frequency_per_microcycle_min=2, frequency_per_microcycle_max=4,
        exercises_per_bodypart_workout_min=0, exercises_per_bodypart_workout_max=3,
        exercise_selection_note=None),
	
    Phase_Breakdown(
        phase_no=4,
        phase="Maximal_Strength",
        component="SAQ",
        subcomponent="strength",
        sub_component="SAQ-strength",
        reps_min=3, reps_max=5,
        sets_min=3, sets_max=4,
        tempo="Fast",
        Seconds_Per_Exercise=None,
        intensity_min=None, intensity_max=None,
        rest_min=30, rest_max=60,
        Required_every_workout=False, Required_within_microcycle="optional but recommended",
        frequency_per_microcycle_min=2, frequency_per_microcycle_max=4,
        exercises_per_bodypart_workout_min=6, exercises_per_bodypart_workout_max=8,
        exercise_selection_note="drills allowing greater horizontal inertia but limited unpredictability"),

    Phase_Breakdown(
        phase_no=4,
        phase="Maximal_Strength",
        component="Resistance",
        subcomponent="strength",
        sub_component="resistance-strength",
        reps_min=1, reps_max=5,
        sets_min=4, sets_max=6,
        tempo="X/X/X",
        Seconds_Per_Exercise=None,
        intensity_min=85, intensity_max=100,
        rest_min=180, rest_max=300,
        Required_every_workout=False, Required_within_microcycle="always",
        frequency_per_microcycle_min=2, frequency_per_microcycle_max=4,
        exercises_per_bodypart_workout_min=1, exercises_per_bodypart_workout_max=3,
        exercise_selection_note=None),
	
    Phase_Breakdown(
        phase_no=5,
        phase="Power",
        component="Flexibility",
        subcomponent="power",
        sub_component="flexibility-power",
        reps_min=10, reps_max=15,
        sets_min=1, sets_max=2,
        tempo="Controlled",
        Seconds_Per_Exercise=None,
        intensity_min=None, intensity_max=None,
        rest_min=0, rest_max=0,
        Required_every_workout=True, Required_within_microcycle="always",
        frequency_per_microcycle_min=NA, frequency_per_microcycle_max=NA,
        exercises_per_bodypart_workout_min=3, exercises_per_bodypart_workout_max=10,
        exercise_selection_note="SMR and dynamic"),

    Phase_Breakdown(
        phase_no=5,
        phase="Power",
        component="Core",
        subcomponent="power",
        sub_component="core-power",
        reps_min=8, reps_max=12,
        sets_min=2, sets_max=3,
        tempo="X/X/X",
        Seconds_Per_Exercise=None,
        intensity_min=None, intensity_max=None,
        rest_min=30, rest_max=60,
        Required_every_workout=False, Required_within_microcycle="can be integrated into warmup or resistance",
        frequency_per_microcycle_min=2, frequency_per_microcycle_max=4,
        exercises_per_bodypart_workout_min=0, exercises_per_bodypart_workout_max=2,
        exercise_selection_note=None),
	
    Phase_Breakdown(
        phase_no=5,
        phase="Power",
        component="Balance",
        subcomponent="power",
        sub_component="balance-power",
        reps_min=8, reps_max=12,
        sets_min=2, sets_max=3,
        tempo="Controlled",
        Seconds_Per_Exercise=None,
        intensity_min=None, intensity_max=None,
        rest_min=30, rest_max=60,
        Required_every_workout=False, Required_within_microcycle="can be integrated into warmup or resistance",
        frequency_per_microcycle_min=2, frequency_per_microcycle_max=4,
        exercises_per_bodypart_workout_min=0, exercises_per_bodypart_workout_max=2,
        exercise_selection_note=None),
	
    Phase_Breakdown(
        phase_no=5,
        phase="Power",
        component="Plyometric",
        subcomponent="power",
        sub_component="plyometric-power",
        reps_min=8, reps_max=12,
        sets_min=2, sets_max=3,
        tempo="X/X/X",
        Seconds_Per_Exercise=None,
        intensity_min=None, intensity_max=None,
        rest_min=30, rest_max=60,
        Required_every_workout=False, Required_within_microcycle="can be integrated into warmup or resistance",
        frequency_per_microcycle_min=2, frequency_per_microcycle_max=4,
        exercises_per_bodypart_workout_min=0, exercises_per_bodypart_workout_max=2,
        exercise_selection_note=None),
	
    Phase_Breakdown(
        phase_no=5,
        phase="Power",
        component="SAQ",
        subcomponent="power",
        sub_component="SAQ-power",
        reps_min=3, reps_max=5,
        sets_min=3, sets_max=5,
        tempo="X/X/X",
        Seconds_Per_Exercise=None,
        intensity_min=None, intensity_max=None,
        rest_min=30, rest_max=90,
        Required_every_workout=False, Required_within_microcycle="can be integrated into warmup or resistance",
        frequency_per_microcycle_min=2, frequency_per_microcycle_max=4,
        exercises_per_bodypart_workout_min=6, exercises_per_bodypart_workout_max=10,
        exercise_selection_note="drills allowing maximal horizontal inertia and unpredictability"),

    Phase_Breakdown(
        phase_no=5,
        phase="Power",
        component="Resistance_Strength",
        subcomponent="strength",
        sub_component="resistance-strength",
        reps_min=1, reps_max=5,
        sets_min=3, sets_max=5,
        tempo="X/X/X ",
        Seconds_Per_Exercise=None,
        intensity_min=85, intensity_max=100,
        rest_min=60, rest_max=120,
        Required_every_workout=False, Required_within_microcycle="always",
        frequency_per_microcycle_min=2, frequency_per_microcycle_max=4,
        exercises_per_bodypart_workout_min=1, exercises_per_bodypart_workout_max=1,
        exercise_selection_note="first part of superset"),

    Phase_Breakdown(
        phase_no=5,
        phase="Power",
        component="Resistance_Power",
        subcomponent="power",
        sub_component="resistance-power",
        reps_min=8, reps_max=10,
        sets_min=3, sets_max=5,
        tempo="X/X/X ",
        Seconds_Per_Exercise=None,
        intensity_min=30, intensity_max=45,
        rest_min=180, rest_max=300,
        Required_every_workout=False, Required_within_microcycle="always",
        frequency_per_microcycle_min=2, frequency_per_microcycle_max=4,
        exercises_per_bodypart_workout_min=1, exercises_per_bodypart_workout_max=1,
        exercise_selection_note="second part of superset"),

]